version: '3'
services:
  db:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data:z
  app:
    build: 
      context: .
      dockerfile: ./docker/app/Dockerfile
    volumes:
      - .:/cookbook
    ports:
      - "3000:3000"
    depends_on:
      - db
  web:
    build: 
      context: .
      dockerfile: ./docker/web/Dockerfile
    depends_on:
      - app
    ports: 
      - 80:80

